### ISSUE TITLE
Add to GPM

### ISSUE THREAD

**Issue by marshmn** [digitregroup/grav-plugin-sentry#1]
This looks like a useful plugin, but it doesn't appear to be registered in GPM? 

It would be good to get this added to GPM so that more people find out about it and to make installation easier.

**Comment by BasileTrujillo** [comment]
Sure! I just completely forgot that Grav maintains it own list of plugin... On my way to add an issue to the Grav project ;)

**Comment by BasileTrujillo** [comment]
Waiting for approval --> https://github.com/getgrav/grav/issues/3038
